//: [Previous](@previous)

import Foundation

//https://projecteuler.net/problem=2


/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var A = 2
var B = 1
var index = 0
var sum = 2
while A < 4000000 && B < 4000000{
    index += 1
    if (index%2)==0{
        A = A + B
      
        if (A%2)==0{
            sum += A
        }
        print(A)
    }else{
       B = A + B
        if (B%2)==0{
            sum += B
        }
        print(B)
   }
}
print("sum \(sum)")
